# Generated by Django 4.1.5 on 2023-01-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_remove_comments_id_comments_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_liked', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_liked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
