# Generated by Django 4.1.5 on 2023-01-08 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_utubeuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utubeuser',
            name='id',
        ),
        migrations.AddField(
            model_name='utubeuser',
            name='Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
