# Generated by Django 4.1.5 on 2023-01-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_channel_channel_owner_alter_video_creator'),
        ('base', '0003_remove_utubeuser_id_utubeuser_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtubeUser',
        ),
    ]
